name = "glow_auth"
version = "0.3.2"

licences = ["Apache-2.0"]
description = "OAuth2 helpers in Gleam..."
repository = { type = "github", user = "adz", repo = "glow_auth" }
links = [{ title = "Website", href = "https://github.com/adz/glow_auth" }]

[dependencies]
gleam_stdlib = "~> 0.22"
gleam_erlang = "~> 0.9"
gleam_http = "~> 3.0"

[dev-dependencies]
gleeunit = "~> 0.6"
